$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$releaseRoot = Join-Path $root "release\cognimail-worker-win"
$iconPath = Join-Path $root "assets\cognimail-worker.ico"
$trayScript = Join-Path $root "scripts\worker-tray.ps1"
$trayExe = Join-Path $releaseRoot "WorkerTray.exe"
$nodeExePath = (Get-Command node).Source

Write-Host "[1/5] Build backend..."
Push-Location $root
npm.cmd run build | Out-Host
Pop-Location

if (Test-Path $releaseRoot) {
  Remove-Item -Recurse -Force $releaseRoot
}
New-Item -ItemType Directory -Path $releaseRoot | Out-Null

Write-Host "[2/5] Copy runtime files..."
Copy-Item -Recurse -Force (Join-Path $root "dist") (Join-Path $releaseRoot "dist")
Copy-Item -Force (Join-Path $root "package.json") (Join-Path $releaseRoot "package.json")
$lockFile = Join-Path $root "package-lock.json"
if (Test-Path $lockFile) {
  Copy-Item -Force $lockFile (Join-Path $releaseRoot "package-lock.json")
}
New-Item -ItemType Directory -Path (Join-Path $releaseRoot "assets") -Force | Out-Null
if (Test-Path $iconPath) {
  Copy-Item -Force $iconPath (Join-Path $releaseRoot "assets/cognimail-worker.ico")
}
Copy-Item -Force $nodeExePath (Join-Path $releaseRoot "node.exe")

@"
# Auto-generated by package-worker.ps1
FIREBASE_WEB_API_KEY=AIzaSyCo1W3Fx8hvUqYB5joqjaAKUMnDAz0fqLM
FIREBASE_AUTH_DOMAIN=cognimail-fa0c0.firebaseapp.com
FIREBASE_PROJECT_ID=cognimail-fa0c0
FIREBASE_STORAGE_BUCKET=cognimail-fa0c0.firebasestorage.app
FIREBASE_MESSAGING_SENDER_ID=906136722896
FIREBASE_APP_ID=1:906136722896:web:3dc2809bf51d11ba302dd5
WORKER_INTERVAL_MINUTES=15
WORKER_LIMIT=5
WORKER_AGENT_PORT=41731
OAUTH_CALLBACK_PORT=1455
"@ | Set-Content -Encoding UTF8 (Join-Path $releaseRoot ".env.worker.userdirect")

@"
@echo off
setlocal
cd /d "%~dp0"
start "" "%~dp0WorkerTray.exe"
exit /b 0
"@ | Set-Content -Encoding ASCII (Join-Path $releaseRoot "run-worker-tray.bat")

Write-Host "[2.5/5] Build tray executable..."
Import-Module ps2exe -ErrorAction SilentlyContinue
if (-not (Get-Command Invoke-ps2exe -ErrorAction SilentlyContinue)) {
  Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
  Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
  Install-Module -Name ps2exe -Scope CurrentUser -Force -AllowClobber
  Import-Module ps2exe
}
Invoke-ps2exe -inputFile $trayScript -outputFile $trayExe -iconFile $iconPath -noConsole -title "CogniMail Worker Tray" -description "CogniMail local worker tray app" -company "CogniMail" -product "CogniMail Worker" -version "1.0.0.0"

@"
COGNIMAIL WORKER (Windows)
==========================

1) Double-click run-worker-tray.bat
   (hoac click thang WorkerTray.exe)
2) Open frontend > Cai dat > Agent cuc bo
3) Click 'Ket noi Agent local' from frontend

Tips:
- Worker runs in system tray with local API (127.0.0.1:41731).
- Worker connects IMAP and writes Firestore directly (no Vercel /emails call).
"@ | Set-Content -Encoding UTF8 (Join-Path $releaseRoot "README-WORKER.txt")

Write-Host "[3/5] Install production dependencies in release folder..."
Push-Location $releaseRoot
if (Test-Path (Join-Path $releaseRoot "package-lock.json")) {
  npm.cmd ci --omit=dev | Out-Host
} else {
  npm.cmd install --omit=dev | Out-Host
}
Pop-Location

Remove-Item (Join-Path $releaseRoot "package.json") -Force -ErrorAction SilentlyContinue
Remove-Item (Join-Path $releaseRoot "package-lock.json") -Force -ErrorAction SilentlyContinue

Write-Host "[4/5] Done."
Write-Host "Release folder: $releaseRoot"
Write-Host "[5/5] Create zip..."
$zipPath = Join-Path $root "release\cognimail-worker-win.zip"
if (Test-Path $zipPath) {
  Remove-Item -Force $zipPath
}
Compress-Archive -Path (Join-Path $releaseRoot "*") -DestinationPath $zipPath -Force
Write-Host "Zip file: $zipPath"
