Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$signature = @"
using System;
using System.Runtime.InteropServices;
public static class Win32 {
  [DllImport("kernel32.dll")] public static extern IntPtr GetConsoleWindow();
  [DllImport("user32.dll")] public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
}
"@
Add-Type -TypeDefinition $signature -Language CSharp

$consolePtr = [Win32]::GetConsoleWindow()
if ($consolePtr -ne [IntPtr]::Zero) {
  [Win32]::ShowWindow($consolePtr, 0) | Out-Null
}

$ErrorActionPreference = "Stop"
$baseDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($baseDir)) {
  $baseDir = [System.AppDomain]::CurrentDomain.BaseDirectory
}
if ([string]::IsNullOrWhiteSpace($baseDir)) {
  throw "Cannot resolve base directory."
}

$root = $baseDir
if (-not (Test-Path (Join-Path $root "dist\worker-user-direct.js"))) {
  $parentDir = Split-Path -Parent $baseDir
  if ($parentDir -and (Test-Path (Join-Path $parentDir "dist\worker-user-direct.js"))) {
    $root = $parentDir
  }
}

$envPath = Join-Path $root ".env.worker.userdirect"
$iconPath = Join-Path $root "assets\\cognimail-worker.ico"
$workerEntry = Join-Path $root "dist\\worker-user-direct.js"
$localNodeExe = Join-Path $root "node.exe"

$workerProcess = $null
$lastTrayState = ""
$lastTrayError = ""
$workerVersion = "5.7.0"
$agentPort = 41731
$agentBaseUrl = "http://127.0.0.1:41731"
$statusIconOn = $null
$statusIconFetching = $null
$statusIconOff = $null
$startupRegPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run"
$startupValueName = "CogniMailWorkerTray"

function New-EnvelopeStatusIcon([System.Drawing.Color]$dotColor) {
  $bitmap = New-Object System.Drawing.Bitmap(16, 16)
  $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
  $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $graphics.Clear([System.Drawing.Color]::Transparent)

  $bodyBrush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(236, 243, 255))
  $borderPen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(41, 64, 107), 1.2)
  $flapPen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(41, 64, 107), 1.2)
  $dotBrush = New-Object System.Drawing.SolidBrush($dotColor)
  $dotBorderPen = New-Object System.Drawing.Pen([System.Drawing.Color]::FromArgb(255, 255, 255), 1)

  $rect = New-Object System.Drawing.Rectangle(2, 3, 12, 9)
  $graphics.FillRectangle($bodyBrush, $rect)
  $graphics.DrawRectangle($borderPen, $rect)
  $graphics.DrawLine($flapPen, 2.6, 4.2, 8, 8.4)
  $graphics.DrawLine($flapPen, 13.4, 4.2, 8, 8.4)

  $graphics.FillEllipse($dotBrush, 10.2, 9.2, 5, 5)
  $graphics.DrawEllipse($dotBorderPen, 10.2, 9.2, 5, 5)

  $hIcon = $bitmap.GetHicon()
  $icon = [System.Drawing.Icon]::FromHandle($hIcon)

  $graphics.Dispose()
  $bodyBrush.Dispose()
  $borderPen.Dispose()
  $flapPen.Dispose()
  $dotBrush.Dispose()
  $dotBorderPen.Dispose()
  $bitmap.Dispose()

  return $icon
}

function Read-EnvMap {
  $map = [ordered]@{}
  if (!(Test-Path $envPath)) { return $map }
  $lines = Get-Content -Path $envPath
  foreach ($line in $lines) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    if ($line.TrimStart().StartsWith("#")) { continue }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { continue }
    $key = $line.Substring(0, $idx).Trim()
    $value = $line.Substring($idx + 1)
    $map[$key] = $value
  }
  return $map
}

function Write-EnvMap([hashtable]$map) {
  $preferredOrder = @(
    "FIREBASE_WEB_API_KEY",
    "FIREBASE_AUTH_DOMAIN",
    "FIREBASE_PROJECT_ID",
    "FIREBASE_STORAGE_BUCKET",
    "FIREBASE_MESSAGING_SENDER_ID",
    "FIREBASE_APP_ID",
    "USER_EMAIL",
    "WORKER_INTERVAL_MINUTES",
    "WORKER_LIMIT",
    "WORKER_AGENT_PORT",
    "OAUTH_CALLBACK_PORT"
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Auto-generated by setup-worker.ps1")
  foreach ($key in $preferredOrder) {
    if ($map.Contains($key)) {
      $lines.Add("$key=$($map[$key])")
      $map.Remove($key) | Out-Null
    }
  }
  foreach ($key in $map.Keys) {
    $lines.Add("$key=$($map[$key])")
  }
  Set-Content -Path $envPath -Value ($lines -join "`r`n") -Encoding UTF8
}

function To-BoundedInt([string]$value, [int]$defaultValue, [int]$minValue, [int]$maxValue) {
  $parsed = 0
  if (![int]::TryParse($value, [ref]$parsed)) {
    return $defaultValue
  }
  if ($parsed -lt $minValue) { return $minValue }
  if ($parsed -gt $maxValue) { return $maxValue }
  return $parsed
}

function Get-StartupCommand {
  $exePath = [System.Windows.Forms.Application]::ExecutablePath
  if ($exePath -and (Test-Path $exePath) -and $exePath.ToLower().EndsWith(".exe")) {
    return "`"$exePath`""
  }
  if ($PSCommandPath -and (Test-Path $PSCommandPath)) {
    return "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$PSCommandPath`""
  }
  return $null
}

function Is-StartupEnabled {
  try {
    $item = Get-ItemProperty -Path $startupRegPath -Name $startupValueName -ErrorAction Stop
    $value = [string]$item.$startupValueName
    return -not [string]::IsNullOrWhiteSpace($value)
  } catch {
    return $false
  }
}

function Set-StartupEnabled([bool]$enabled) {
  if (!(Test-Path $startupRegPath)) {
    New-Item -Path $startupRegPath -Force | Out-Null
  }
  if ($enabled) {
    $command = Get-StartupCommand
    if ([string]::IsNullOrWhiteSpace($command)) {
      throw "Khong tao duoc lenh startup."
    }
    Set-ItemProperty -Path $startupRegPath -Name $startupValueName -Value $command -Type String
    return
  }
  Remove-ItemProperty -Path $startupRegPath -Name $startupValueName -ErrorAction SilentlyContinue
}

function Test-WorkerEnvReady {
  if (!(Test-Path $envPath)) { return $false }
  $raw = Get-Content -Path $envPath -Raw
  return $raw -match "FIREBASE_WEB_API_KEY="
}

function Refresh-AgentBaseUrl {
  $script:agentBaseUrl = "http://127.0.0.1:$agentPort"
}

function Find-WorkerPids {
  try {
    $needle = [Regex]::Escape($workerEntry)
    $processes = Get-CimInstance Win32_Process -Filter "Name='node.exe'" -ErrorAction SilentlyContinue
    if (-not $processes) { return @() }
    return @(
      $processes |
        Where-Object { $_.CommandLine -and ($_.CommandLine -match "worker-user-direct\.js" -or $_.CommandLine -match $needle) } |
        ForEach-Object { [int]$_.ProcessId }
    )
  } catch {
    return @()
  }
}

function Start-Worker {
  Refresh-AgentBaseUrl
  try {
    $existing = Invoke-RestMethod -Uri "$($script:agentBaseUrl)/ping" -Method Get -TimeoutSec 2
    if ($existing -and $existing.ok) { return }
  } catch {}
  if ($script:workerProcess -and -not $script:workerProcess.HasExited) { return }
  foreach ($workerPid in (Find-WorkerPids)) {
    try { Stop-Process -Id $workerPid -Force -ErrorAction SilentlyContinue } catch {}
  }
  if (!(Test-WorkerEnvReady)) {
    $base = [ordered]@{
      FIREBASE_WEB_API_KEY = "AIzaSyCo1W3Fx8hvUqYB5joqjaAKUMnDAz0fqLM"
      FIREBASE_AUTH_DOMAIN = "cognimail-fa0c0.firebaseapp.com"
      FIREBASE_PROJECT_ID = "cognimail-fa0c0"
      FIREBASE_STORAGE_BUCKET = "cognimail-fa0c0.firebasestorage.app"
      FIREBASE_MESSAGING_SENDER_ID = "906136722896"
      FIREBASE_APP_ID = "1:906136722896:web:3dc2809bf51d11ba302dd5"
      WORKER_INTERVAL_MINUTES = "15"
      WORKER_LIMIT = "5"
      WORKER_AGENT_PORT = "41731"
      OAUTH_CALLBACK_PORT = "1455"
    }
    Write-EnvMap $base
  }

  if (!(Test-Path $workerEntry)) {
    [System.Windows.Forms.MessageBox]::Show("Thieu file dist\\worker-user-direct.js. Hay giai nen toan bo file zip worker vao 1 thu muc rieng, sau do chay lai WorkerTray.exe.", "CogniMail Worker", "OK", "Error") | Out-Null
    return
  }

  $nodeCmd = if (Test-Path $localNodeExe) { $localNodeExe } else { "node" }

  if ($nodeCmd -eq "node") {
    $nodeAvailable = Get-Command node -ErrorAction SilentlyContinue
    if (-not $nodeAvailable) {
      [System.Windows.Forms.MessageBox]::Show("Khong tim thay node runtime. Hay dung ban worker dong goi chuan (co node.exe).", "CogniMail Worker", "OK", "Error") | Out-Null
      return
    }
  }

  $oldEnv = $env:WORKER_ENV_PATH
  $env:WORKER_ENV_PATH = $envPath
  try {
    $script:workerProcess = Start-Process -FilePath $nodeCmd -ArgumentList "`"$workerEntry`"" -WorkingDirectory $root -WindowStyle Hidden -PassThru
  } finally {
    if ([string]::IsNullOrEmpty($oldEnv)) {
      Remove-Item Env:WORKER_ENV_PATH -ErrorAction SilentlyContinue
    } else {
      $env:WORKER_ENV_PATH = $oldEnv
    }
  }
}

function Stop-Worker {
  if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
    try { Stop-Process -Id $script:workerProcess.Id -Force } catch {}
  }
  foreach ($workerPid in (Find-WorkerPids)) {
    try { Stop-Process -Id $workerPid -Force -ErrorAction SilentlyContinue } catch {}
  }
  $script:workerProcess = $null
}

function Invoke-AgentHealth {
  Refresh-AgentBaseUrl
  try {
    $res = Invoke-RestMethod -Uri "$($script:agentBaseUrl)/status" -Method Get -TimeoutSec 4
    $msg = "Version: $($res.version)`nAgent OK`nSyncing: $($res.syncing)`nInterval: $($res.intervalMinutes)m`nLimit: $($res.fetchLimit)`nLastRun: $($res.lastRunAt)`nLastError: $($res.lastError)"
    [System.Windows.Forms.MessageBox]::Show($msg, "CogniMail Worker", "OK", "Information") | Out-Null
  } catch {
    [System.Windows.Forms.MessageBox]::Show("Khong ket noi duoc agent local (127.0.0.1:41731)", "CogniMail Worker", "OK", "Warning") | Out-Null
  }
}

function Get-AgentPing {
  Refresh-AgentBaseUrl
  return Invoke-RestMethod -Uri "$($script:agentBaseUrl)/ping" -Method Get -TimeoutSec 8
}

function Get-AgentHealth {
  Refresh-AgentBaseUrl
  return Invoke-RestMethod -Uri "$($script:agentBaseUrl)/status" -Method Get -TimeoutSec 15
}

function Set-TrayState([string]$state, [string]$errorMessage) {
  if ($state -eq $script:lastTrayState -and $errorMessage -eq $script:lastTrayError) { return }
  $script:lastTrayState = $state
  $script:lastTrayError = $errorMessage

  switch ($state) {
    "fetching" {
      $notifyIcon.Icon = $statusIconFetching
      $notifyIcon.Text = "CogniMail Worker - Dang lay thu"
      $notifyIcon.BalloonTipTitle = "CogniMail Worker"
      $notifyIcon.BalloonTipText = "Dang lay email tu IMAP..."
      $notifyIcon.ShowBalloonTip(1500)
    }
    "on" {
      $notifyIcon.Icon = $statusIconOn
      $notifyIcon.Text = "CogniMail Worker - Da bat"
      $notifyIcon.BalloonTipTitle = "CogniMail Worker"
      $notifyIcon.BalloonTipText = "Worker da online, san sang nhan lenh."
      $notifyIcon.ShowBalloonTip(1200)
    }
    "error" {
      $notifyIcon.Icon = $statusIconOff
      $notifyIcon.Text = "CogniMail Worker - Loi"
      $notifyIcon.BalloonTipTitle = "CogniMail Worker - Loi"
      $notifyIcon.BalloonTipText = if ($errorMessage) { $errorMessage } else { "Agent gap loi." }
      $notifyIcon.ShowBalloonTip(2500)
    }
    "starting" {
      $notifyIcon.Icon = $statusIconOff
      $notifyIcon.Text = "CogniMail Worker - Dang khoi dong lai"
    }
    "off" {
      $notifyIcon.Icon = $statusIconOff
      $notifyIcon.Text = "CogniMail Worker - Dang tat"
    }
    default {
      $notifyIcon.Icon = $statusIconOff
      $notifyIcon.Text = "CogniMail Worker - Dang tat"
    }
  }
}

function Refresh-TrayStatus {
  try {
    $ping = Get-AgentPing
    if (-not $ping.ok) {
      Set-TrayState "off" ""
      return
    }
    $res = Get-AgentHealth
    if ($res.syncing -or $res.stage -eq "fetching-imap" -or $res.stage -eq "saving-firestore") {
      Set-TrayState "fetching" ""
      return
    }
    if ($res.lastError) {
      Set-TrayState "error" "$($res.lastError)"
      return
    }
    Set-TrayState "on" ""
  } catch {
    $workerCount = (Find-WorkerPids).Count
    if ($workerCount -eq 0) {
      Set-TrayState "starting" ""
      Start-Worker
      return
    }
    if ($script:lastTrayState -eq "fetching") {
      Set-TrayState "fetching" "Worker dang ban, trang thai tra ve cham."
      return
    }
    Set-TrayState "on" "Worker dang chay, nhung status timeout tam thoi."
  }
}

function Invoke-AgentSyncNow {
  Refresh-AgentBaseUrl
  try {
    $res = Invoke-RestMethod -Uri "$($script:agentBaseUrl)/sync-now" -Method Post -TimeoutSec 120
    $msg = "Dong bo xong`nLastRun: $($res.lastRunAt)`nFetched: $($res.lastResult.fetched)`nSaved: $($res.lastResult.saved)"
    [System.Windows.Forms.MessageBox]::Show($msg, "CogniMail Worker", "OK", "Information") | Out-Null
  } catch {
    [System.Windows.Forms.MessageBox]::Show("Sync-now that bai: $($_.Exception.Message)", "CogniMail Worker", "OK", "Error") | Out-Null
  }
}

$logForm = $null
$logTextBox = $null
$logTimer = $null
$lastLogSeq = 0

function Append-AgentEventsToLog {
  if (-not $script:logTextBox -or $script:logTextBox.IsDisposed) { return }
  Refresh-AgentBaseUrl
  try {
    $res = Invoke-RestMethod -Uri "$($script:agentBaseUrl)/events?since=$lastLogSeq" -Method Get -TimeoutSec 3
    if (-not $res.ok) { return }
    $nextSeq = $script:lastLogSeq
    if ($null -ne $res.latestSeq) {
      $trySeq = 0
      if ([int]::TryParse("$($res.latestSeq)", [ref]$trySeq)) {
        $nextSeq = $trySeq
      }
    }
    $script:lastLogSeq = $nextSeq
    if ($res.events -and $res.events.Count -gt 0) {
      $lines = @()
      foreach ($item in $res.events) {
        if ($item.line) { $lines += [string]$item.line }
      }
      if ($lines.Count -gt 0) {
        if ($script:logTextBox.TextLength -gt 0) { $script:logTextBox.AppendText("`r`n") }
        $script:logTextBox.AppendText(($lines -join "`r`n"))
        if ($script:logTextBox.TextLength -gt 30000) {
          $script:logTextBox.Text = $script:logTextBox.Text.Substring($script:logTextBox.TextLength - 15000)
        }
        $script:logTextBox.SelectionStart = $script:logTextBox.TextLength
        $script:logTextBox.ScrollToCaret()
      }
    }
  } catch {
    # keep silent to avoid lag popup
  }
}

function Open-LogWindow {
  if ($script:logForm -and -not $script:logForm.IsDisposed) {
    $script:logForm.Activate()
    return
  }

  $script:logForm = New-Object System.Windows.Forms.Form
  $script:logForm.Text = "CogniMail Worker - Log"
  $script:logForm.StartPosition = "CenterScreen"
  $script:logForm.Size = New-Object System.Drawing.Size(760, 460)
  $script:logForm.TopMost = $false

  $script:logTextBox = New-Object System.Windows.Forms.TextBox
  $script:logTextBox.Multiline = $true
  $script:logTextBox.ReadOnly = $true
  $script:logTextBox.ScrollBars = "Vertical"
  $script:logTextBox.Dock = "Fill"
  $script:logTextBox.Font = New-Object System.Drawing.Font("Consolas", 9)
  $script:logTextBox.Text = "Dang tai log..."
  $script:logForm.Controls.Add($script:logTextBox)

  $refreshPanel = New-Object System.Windows.Forms.Panel
  $refreshPanel.Dock = "Top"
  $refreshPanel.Height = 42

  $refreshButton = New-Object System.Windows.Forms.Button
  $refreshButton.Text = "Lam moi"
  $refreshButton.Width = 90
  $refreshButton.Height = 28
  $refreshButton.Location = New-Object System.Drawing.Point(10, 7)
  $refreshButton.Add_Click({
    if (-not $script:logTextBox -or $script:logTextBox.IsDisposed) { return }
    $script:lastLogSeq = 0
    $script:logTextBox.Clear()
    Append-AgentEventsToLog
  })
  $refreshPanel.Controls.Add($refreshButton)
  $script:logForm.Controls.Add($refreshPanel)
  $refreshPanel.BringToFront()

  $script:logTimer = New-Object System.Windows.Forms.Timer
  $script:logTimer.Interval = 2500
  $script:logTimer.Add_Tick({
    Append-AgentEventsToLog
  })
  $script:logTimer.Start()
  $script:lastLogSeq = 0
  Append-AgentEventsToLog

  $script:logForm.Add_FormClosed({
    if ($script:logTimer) {
      $script:logTimer.Stop()
      $script:logTimer.Dispose()
      $script:logTimer = $null
    }
    $script:logTextBox = $null
    $script:logForm = $null
  })

  $script:logForm.Show()
}

function Open-SettingsDialog {
  if (!(Test-Path $envPath)) {
    Write-EnvMap ([ordered]@{
      FIREBASE_WEB_API_KEY = "AIzaSyCo1W3Fx8hvUqYB5joqjaAKUMnDAz0fqLM"
      FIREBASE_AUTH_DOMAIN = "cognimail-fa0c0.firebaseapp.com"
      FIREBASE_PROJECT_ID = "cognimail-fa0c0"
      FIREBASE_STORAGE_BUCKET = "cognimail-fa0c0.firebasestorage.app"
      FIREBASE_MESSAGING_SENDER_ID = "906136722896"
      FIREBASE_APP_ID = "1:906136722896:web:3dc2809bf51d11ba302dd5"
      WORKER_INTERVAL_MINUTES = "15"
      WORKER_LIMIT = "5"
      WORKER_AGENT_PORT = "41731"
      OAUTH_CALLBACK_PORT = "1455"
    })
  }

  $envMap = Read-EnvMap
  $currentInterval = To-BoundedInt "$($envMap['WORKER_INTERVAL_MINUTES'])" 15 1 120
  $currentLimit = To-BoundedInt "$($envMap['WORKER_LIMIT'])" 5 1 100

  $form = New-Object System.Windows.Forms.Form
  $form.Text = "CogniMail Worker - Cai dat"
  $form.StartPosition = "CenterScreen"
  $form.Size = New-Object System.Drawing.Size(360, 230)
  $form.FormBorderStyle = "FixedDialog"
  $form.MaximizeBox = $false
  $form.MinimizeBox = $false
  $form.TopMost = $true
  $form.Size = New-Object System.Drawing.Size(360, 270)

  $labelInterval = New-Object System.Windows.Forms.Label
  $labelInterval.Text = "Chu ky lay mail (phut):"
  $labelInterval.AutoSize = $true
  $labelInterval.Location = New-Object System.Drawing.Point(20, 22)

  $numInterval = New-Object System.Windows.Forms.NumericUpDown
  $numInterval.Location = New-Object System.Drawing.Point(23, 45)
  $numInterval.Size = New-Object System.Drawing.Size(140, 24)
  $numInterval.Minimum = 1
  $numInterval.Maximum = 120
  $numInterval.Value = $currentInterval

  $labelLimit = New-Object System.Windows.Forms.Label
  $labelLimit.Text = "So email moi lan lay:"
  $labelLimit.AutoSize = $true
  $labelLimit.Location = New-Object System.Drawing.Point(20, 85)

  $numLimit = New-Object System.Windows.Forms.NumericUpDown
  $numLimit.Location = New-Object System.Drawing.Point(23, 108)
  $numLimit.Size = New-Object System.Drawing.Size(140, 24)
  $numLimit.Minimum = 1
  $numLimit.Maximum = 100
  $numLimit.Value = $currentLimit

  $chkStartup = New-Object System.Windows.Forms.CheckBox
  $chkStartup.Text = "Tu chay cung Windows"
  $chkStartup.AutoSize = $true
  $chkStartup.Location = New-Object System.Drawing.Point(23, 142)
  $chkStartup.Checked = Is-StartupEnabled

  $hint = New-Object System.Windows.Forms.Label
  $hint.Text = "Luu xong se ap dung o lan chay tiep theo. Neu worker dang chay, ban co the restart ngay."
  $hint.AutoSize = $false
  $hint.Size = New-Object System.Drawing.Size(310, 36)
  $hint.Location = New-Object System.Drawing.Point(20, 166)

  $btnSave = New-Object System.Windows.Forms.Button
  $btnSave.Text = "Luu"
  $btnSave.Location = New-Object System.Drawing.Point(170, 45)
  $btnSave.Size = New-Object System.Drawing.Size(75, 28)

  $btnCancel = New-Object System.Windows.Forms.Button
  $btnCancel.Text = "Dong"
  $btnCancel.Location = New-Object System.Drawing.Point(255, 45)
  $btnCancel.Size = New-Object System.Drawing.Size(75, 28)

  $btnSave.Add_Click({
    $newInterval = [int]$numInterval.Value
    $newLimit = [int]$numLimit.Value
    $envMap['WORKER_INTERVAL_MINUTES'] = "$newInterval"
    $envMap['WORKER_LIMIT'] = "$newLimit"
    Write-EnvMap $envMap
    Set-StartupEnabled ([bool]$chkStartup.Checked)
    if ($script:startupItemRef) {
      $script:startupItemRef.Checked = Is-StartupEnabled
    }

    $restart = [System.Windows.Forms.DialogResult]::No
    if ($script:workerProcess -and -not $script:workerProcess.HasExited) {
      $restart = [System.Windows.Forms.MessageBox]::Show(
        "Da luu cau hinh. Ban muon restart worker ngay de ap dung khong?",
        "CogniMail Worker",
        [System.Windows.Forms.MessageBoxButtons]::YesNo,
        [System.Windows.Forms.MessageBoxIcon]::Question
      )
      if ($restart -eq [System.Windows.Forms.DialogResult]::Yes) {
        Stop-Worker
        Start-Worker
      }
    }

    if ($restart -ne [System.Windows.Forms.DialogResult]::Yes) {
      [System.Windows.Forms.MessageBox]::Show("Da luu cau hinh thanh cong.", "CogniMail Worker", "OK", "Information") | Out-Null
    }
    $form.Close()
  })

  $btnCancel.Add_Click({ $form.Close() })

  $form.Controls.Add($labelInterval)
  $form.Controls.Add($numInterval)
  $form.Controls.Add($labelLimit)
  $form.Controls.Add($numLimit)
  $form.Controls.Add($chkStartup)
  $form.Controls.Add($hint)
  $form.Controls.Add($btnSave)
  $form.Controls.Add($btnCancel)
  $form.ShowDialog() | Out-Null
}

$notifyIcon = New-Object System.Windows.Forms.NotifyIcon
$statusIconOn = New-EnvelopeStatusIcon ([System.Drawing.Color]::FromArgb(59,130,246))
$statusIconFetching = New-EnvelopeStatusIcon ([System.Drawing.Color]::FromArgb(34,197,94))
$statusIconOff = New-EnvelopeStatusIcon ([System.Drawing.Color]::FromArgb(239,68,68))
$notifyIcon.Icon = $statusIconOff
$notifyIcon.Text = "CogniMail Worker"
$notifyIcon.Visible = $true

$menu = New-Object System.Windows.Forms.ContextMenuStrip
$startItem = $menu.Items.Add("Bat worker")
$stopItem = $menu.Items.Add("Dung worker")
$settingsItem = $menu.Items.Add("Cai dat (dung tren Frontend)")
$startupItem = New-Object System.Windows.Forms.ToolStripMenuItem
$startupItem.Text = "Tu chay cung Windows"
$startupItem.CheckOnClick = $true
$startupItem.Checked = Is-StartupEnabled
$menu.Items.Add($startupItem) | Out-Null
$script:startupItemRef = $startupItem
$healthItem = $menu.Items.Add("Kiem tra agent")
$logsItem = $menu.Items.Add("Xem log")
$syncItem = $menu.Items.Add("Sync ngay")
$openItem = $menu.Items.Add("Mo thu muc")
$versionItem = $menu.Items.Add("Phien ban $workerVersion")
$menu.Items.Add("-") | Out-Null
$exitItem = $menu.Items.Add("Thoat")

$startItem.add_Click({ Start-Worker })
$stopItem.add_Click({ Stop-Worker })
$settingsItem.Enabled = $false
$startupItem.add_CheckedChanged({
  try {
    Set-StartupEnabled ([bool]$startupItem.Checked)
    if ($startupItem.Checked) {
      $notifyIcon.BalloonTipTitle = "CogniMail Worker"
      $notifyIcon.BalloonTipText = "Da bat tu chay cung Windows."
      $notifyIcon.ShowBalloonTip(1200)
    } else {
      $notifyIcon.BalloonTipTitle = "CogniMail Worker"
      $notifyIcon.BalloonTipText = "Da tat tu chay cung Windows."
      $notifyIcon.ShowBalloonTip(1200)
    }
  } catch {
    $startupItem.Checked = Is-StartupEnabled
    [System.Windows.Forms.MessageBox]::Show("Khong doi duoc che do startup: $($_.Exception.Message)", "CogniMail Worker", "OK", "Error") | Out-Null
  }
})
$healthItem.add_Click({ Invoke-AgentHealth })
$logsItem.add_Click({ Open-LogWindow })
$syncItem.add_Click({ Invoke-AgentSyncNow })
$openItem.add_Click({ Start-Process explorer.exe $root })
$versionItem.Enabled = $false
$exitItem.add_Click({
  Stop-Worker
  $notifyIcon.Visible = $false
  [System.Windows.Forms.Application]::Exit()
})

$notifyIcon.ContextMenuStrip = $menu
$notifyIcon.add_DoubleClick({ Invoke-AgentHealth })

Start-Worker
[void](Refresh-TrayStatus)

$statusTimer = New-Object System.Windows.Forms.Timer
$statusTimer.Interval = 10000
$statusTimer.Add_Tick({ Refresh-TrayStatus })
$statusTimer.Start()
[System.Windows.Forms.Application]::Run()
